version: '3.1'

services:
  db:
    platform: linux/x86_64
    container_name: postgres_database
    image: postgres
    restart: always
    env_file: .env.development
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'